language: ruby

sudo: false
dist: trusty

rvm:
  - 2.2
  - 2.1
  - 2.0
  - 1.9
  - jruby-9.1.9.0

matrix:
  include:
    - rvm: 1.8.7
      gemfile: gemfiles/Gemfile-1.8.7
    - rvm: jruby-18mode
      gemfile: gemfiles/Gemfile-1.8.7
